version: '2'

services:
  dmall-registry-server:
      image: dmall-docker-registry:5000/dmall/inventory-service:$BUILD_NUMBER
      mem_limit: 512m
      networks:
          - jenkins_dmall-network
      ports:
          - "8082:8082"

networks:
  jenkins_dmall-network:
    external: true