version: '2'

services:
  dmall-registry-server:
      image: 10.204.21.177:5000/dmall/inventory-service:latest
      mem_limit: 512m
      networks:
          - jenkins_dmall-network
      ports:
          - "8082:8082"

networks:
  jenkins_dmall-network:
    external: true